### ISSUE TITLE
Error: Dynamic require of "stylelint" is not supported

### ISSUE THREAD

**Issue by hackyoMa** [ModyQyW/vite-plugin-stylelint#16]
`pnpm create vite my-vue-app --template vue-ts`
`pnpm install stylelint@^14 -D`
`pnpm install vite-plugin-stylelint -D`
`plugins: [vue(), StylelintPlugin()]`
`pnpm run dev`

details: 

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/18374520/179440397-40b5037b-f992-43e3-900e-26b24a312ad7.png">

**Comment by hackyoMa** [comment]
I'm not sure if it's a problem with upgrading vite to 3.0.0

**Comment by ModyQyW** [comment]
I have updated 5 projects to vite 3 but haven't seen such error. I need some time to research.

**Comment by ModyQyW** [comment]
Removing `type: "module"` in package.json should be a solution.

**Comment by ModyQyW** [comment]
This package is bundled by tsup (esbuild underhood) and targets at node12. Please track https://github.com/evanw/esbuild/pull/2067, https://github.com/evanw/esbuild/issues/1921 and https://github.com/evanw/esbuild/issues/2111.

Maybe change to unbuild in the future if necessary, since official plugins have changed to unbuild already.

**Comment by hackyoMa** [comment]
I understand, thank you for your support

**Comment by bleakwind** [comment]
Please change to unbuild!!!

**Comment by ModyQyW** [comment]
`type: "module"` support should be fixed in v3.0.3. Please have a try.

I don't have much time to change to unbuild recently. PR welcome.

**Comment by ModyQyW** [comment]
`type: "module"` support should be fixed in v3.0.3. Please have a try.

I don't have much time to change to unbuild recently. PR welcome.
